-- 회원가입 DB 만들기

-- H2 Database SQL

-- 테이블 삭제
DROP TABLE IF EXISTS member CASCADE;

-- 테이블 생성
-- H2DB SQL 문법
CREATE TABLE member (
    id bigint generated by default as identity,
    user_id varchar(255),
    user_pw varchar(255),
    user_name varchar(255),
    user_role  varchar(255),
    joindate date default CURRENT_TIMESTAMP()
)

-- ROW 추가
INSERT INTO member(user_id,user_pw,user_name,user_role,joindate)
values
('hong', '1234', '홍길동','ROLE_USER','2023-09-01'),
('kong', '1234', '콩길동','ROLE_USER','2023-09-02'),
('gong', '1234', '공길동','ROLE_USER','2023-09-03'),
('bong', '1234', '봉길동','ROLE_USER','2023-09-04'),
('pong', '1234', '퐁길동','ROLE_ADMIN','2023-09-05');

-- 검색하기
SELECT * FROM member;

-- 커밋하기
commit;